I am a log file
I have not been tampered with
I hold records
that show
who has been denied access to things
I am useful for assigning blame
and sometimes for fixing things
but always for proving innocence
